version: "3.9"

services:
  api:
    build: ./api
    container_name: flask_api
    ports:
      - "5000:5000"

  streamlit:
    build: ./streamlit_app
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:5000/analyze
    depends_on:
      - api
